//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.23 at 04:03:10 PM CST 
//

package com.newegg.marketplace.sdk.rma.model;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="IsSuccess"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="true"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OperationType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="IssueRMAResponse"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SellerID"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ResponseBody"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="RMAInfo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;all&gt;
 *                             &lt;element name="RMANumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                             &lt;element name="RMAType"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                                   &lt;minInclusive value="1"/&gt;
 *                                   &lt;maxInclusive value="2"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="RMATypeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="SellerRMANumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IssueUser"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="RMADate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="RMAStatus" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="RMAStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="RMAShipMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="RMAShipMethodDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="OrderAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                             &lt;element name="AvailableRefundAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                             &lt;element name="RMAProcessedBy" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="newegg"/&gt;
 *                                   &lt;enumeration value="seller"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="RMAReceiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="RMANote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PriorRefundAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                             &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="CustomerPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="CustomerEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToCityName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToStateCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ShipToCompany" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="RMATransactionList"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence maxOccurs="unbounded"&gt;
 *                                       &lt;element name="RMATransaction"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;all&gt;
 *                                                 &lt;element name="SellerPartNumber"&gt;
 *                                                   &lt;simpleType&gt;
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                                     &lt;/restriction&gt;
 *                                                   &lt;/simpleType&gt;
 *                                                 &lt;/element&gt;
 *                                                 &lt;element name="MfrPartNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="NeweggItemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                                 &lt;element name="ReturnQuantity"&gt;
 *                                                   &lt;simpleType&gt;
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                                                       &lt;minInclusive value="1"/&gt;
 *                                                     &lt;/restriction&gt;
 *                                                   &lt;/simpleType&gt;
 *                                                 &lt;/element&gt;
 *                                                 &lt;element name="ReturnUnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                                                 &lt;element name="RefundShippingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                                 &lt;element name="ShippedBy" minOccurs="0"&gt;
 *                                                   &lt;simpleType&gt;
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                                       &lt;enumeration value="0"/&gt;
 *                                                       &lt;enumeration value="1"/&gt;
 *                                                     &lt;/restriction&gt;
 *                                                   &lt;/simpleType&gt;
 *                                                 &lt;/element&gt;
 *                                                 &lt;element name="RefundShipppingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                                                 &lt;element name="RMAReason"&gt;
 *                                                   &lt;simpleType&gt;
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                                                       &lt;minInclusive value="1"/&gt;
 *                                                       &lt;maxInclusive value="9"/&gt;
 *                                                     &lt;/restriction&gt;
 *                                                   &lt;/simpleType&gt;
 *                                                 &lt;/element&gt;
 *                                                 &lt;element name="RMAReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/all&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/all&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Memo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ResponseDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "NeweggAPIResponse")
public class SubmitRMAResponse {

	@XmlElement(name = "IsSuccess", required = true)
	@JsonProperty("IsSuccess")
	private String isSuccess;

	@XmlElement(name = "OperationType", required = true)
	@JsonProperty("OperationType")
	private String operationType;

	@XmlElement(name = "SellerID", required = true)
	@JsonProperty("SellerID")
	private String sellerID;

	@XmlElement(name = "ResponseBody", required = true)
	@JsonProperty("ResponseBody")
	private SubmitRMAResponse.ResponseBody responseBody;

	@XmlElement(name = "Memo")
	@JsonProperty("Memo")
	private String memo;

	@XmlElement(name = "ResponseDate", required = true)
	@JsonProperty("ResponseDate")
	private String responseDate;

	public String getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}

	public String getOperationType() {
		return operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	public String getSellerID() {
		return sellerID;
	}

	public void setSellerID(String sellerID) {
		this.sellerID = sellerID;
	}

	public SubmitRMAResponse.ResponseBody getResponseBody() {
		return responseBody;
	}

	public void setResponseBody(SubmitRMAResponse.ResponseBody responseBody) {
		this.responseBody = responseBody;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getResponseDate() {
		return responseDate;
	}

	public void setResponseDate(String responseDate) {
		this.responseDate = responseDate;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;all&gt;
	 *         &lt;element name="RMAInfo"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;all&gt;
	 *                   &lt;element name="RMANumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
	 *                   &lt;element name="RMAType"&gt;
	 *                     &lt;simpleType&gt;
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
	 *                         &lt;minInclusive value="1"/&gt;
	 *                         &lt;maxInclusive value="2"/&gt;
	 *                       &lt;/restriction&gt;
	 *                     &lt;/simpleType&gt;
	 *                   &lt;/element&gt;
	 *                   &lt;element name="RMATypeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="SellerRMANumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="IssueUser"&gt;
	 *                     &lt;simpleType&gt;
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
	 *                       &lt;/restriction&gt;
	 *                     &lt;/simpleType&gt;
	 *                   &lt;/element&gt;
	 *                   &lt;element name="RMADate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="RMAStatus" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
	 *                   &lt;element name="RMAStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="RMAShipMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
	 *                   &lt;element name="RMAShipMethodDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
	 *                   &lt;element name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
	 *                   &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
	 *                   &lt;element name="OrderAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
	 *                   &lt;element name="AvailableRefundAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
	 *                   &lt;element name="RMAProcessedBy" minOccurs="0"&gt;
	 *                     &lt;simpleType&gt;
	 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
	 *                         &lt;enumeration value="newegg"/&gt;
	 *                         &lt;enumeration value="seller"/&gt;
	 *                       &lt;/restriction&gt;
	 *                     &lt;/simpleType&gt;
	 *                   &lt;/element&gt;
	 *                   &lt;element name="RMAReceiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="RMANote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
	 *                   &lt;element name="PriorRefundAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
	 *                   &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="CustomerPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="CustomerEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToCityName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToStateCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="ShipToCompany" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                   &lt;element name="RMATransactionList"&gt;
	 *                     &lt;complexType&gt;
	 *                       &lt;complexContent&gt;
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                           &lt;sequence maxOccurs="unbounded"&gt;
	 *                             &lt;element name="RMATransaction"&gt;
	 *                               &lt;complexType&gt;
	 *                                 &lt;complexContent&gt;
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                                     &lt;all&gt;
	 *                                       &lt;element name="SellerPartNumber"&gt;
	 *                                         &lt;simpleType&gt;
	 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
	 *                                           &lt;/restriction&gt;
	 *                                         &lt;/simpleType&gt;
	 *                                       &lt;/element&gt;
	 *                                       &lt;element name="MfrPartNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                                       &lt;element name="NeweggItemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                                       &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
	 *                                       &lt;element name="ReturnQuantity"&gt;
	 *                                         &lt;simpleType&gt;
	 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
	 *                                             &lt;minInclusive value="1"/&gt;
	 *                                           &lt;/restriction&gt;
	 *                                         &lt;/simpleType&gt;
	 *                                       &lt;/element&gt;
	 *                                       &lt;element name="ReturnUnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
	 *                                       &lt;element name="RefundShippingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
	 *                                       &lt;element name="ShippedBy" minOccurs="0"&gt;
	 *                                         &lt;simpleType&gt;
	 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
	 *                                             &lt;enumeration value="0"/&gt;
	 *                                             &lt;enumeration value="1"/&gt;
	 *                                           &lt;/restriction&gt;
	 *                                         &lt;/simpleType&gt;
	 *                                       &lt;/element&gt;
	 *                                       &lt;element name="RefundShipppingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
	 *                                       &lt;element name="RMAReason"&gt;
	 *                                         &lt;simpleType&gt;
	 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
	 *                                             &lt;minInclusive value="1"/&gt;
	 *                                             &lt;maxInclusive value="9"/&gt;
	 *                                           &lt;/restriction&gt;
	 *                                         &lt;/simpleType&gt;
	 *                                       &lt;/element&gt;
	 *                                       &lt;element name="RMAReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
	 *                                     &lt;/all&gt;
	 *                                   &lt;/restriction&gt;
	 *                                 &lt;/complexContent&gt;
	 *                               &lt;/complexType&gt;
	 *                             &lt;/element&gt;
	 *                           &lt;/sequence&gt;
	 *                         &lt;/restriction&gt;
	 *                       &lt;/complexContent&gt;
	 *                     &lt;/complexType&gt;
	 *                   &lt;/element&gt;
	 *                 &lt;/all&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/all&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {

	})
	public static class ResponseBody {

		@XmlElement(name = "RMAInfo", required = true)
		@JsonProperty("RMAInfo")
		private SubmitRMAResponse.ResponseBody.RMAInfo rmaInfo;

		public SubmitRMAResponse.ResponseBody.RMAInfo getRmaInfo() {
			return rmaInfo;
		}

		public void setRmaInfo(SubmitRMAResponse.ResponseBody.RMAInfo rmaInfo) {
			this.rmaInfo = rmaInfo;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;all&gt;
		 *         &lt;element name="RMANumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
		 *         &lt;element name="RMAType"&gt;
		 *           &lt;simpleType&gt;
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
		 *               &lt;minInclusive value="1"/&gt;
		 *               &lt;maxInclusive value="2"/&gt;
		 *             &lt;/restriction&gt;
		 *           &lt;/simpleType&gt;
		 *         &lt;/element&gt;
		 *         &lt;element name="RMATypeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="SellerRMANumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="IssueUser"&gt;
		 *           &lt;simpleType&gt;
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
		 *             &lt;/restriction&gt;
		 *           &lt;/simpleType&gt;
		 *         &lt;/element&gt;
		 *         &lt;element name="RMADate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="RMAStatus" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
		 *         &lt;element name="RMAStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="RMAShipMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
		 *         &lt;element name="RMAShipMethodDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
		 *         &lt;element name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
		 *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
		 *         &lt;element name="OrderAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
		 *         &lt;element name="AvailableRefundAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
		 *         &lt;element name="RMAProcessedBy" minOccurs="0"&gt;
		 *           &lt;simpleType&gt;
		 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
		 *               &lt;enumeration value="newegg"/&gt;
		 *               &lt;enumeration value="seller"/&gt;
		 *             &lt;/restriction&gt;
		 *           &lt;/simpleType&gt;
		 *         &lt;/element&gt;
		 *         &lt;element name="RMAReceiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="RMANote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
		 *         &lt;element name="PriorRefundAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
		 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="CustomerPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="CustomerEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToCityName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToStateCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToZipCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="ShipToCompany" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *         &lt;element name="RMATransactionList"&gt;
		 *           &lt;complexType&gt;
		 *             &lt;complexContent&gt;
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *                 &lt;sequence maxOccurs="unbounded"&gt;
		 *                   &lt;element name="RMATransaction"&gt;
		 *                     &lt;complexType&gt;
		 *                       &lt;complexContent&gt;
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *                           &lt;all&gt;
		 *                             &lt;element name="SellerPartNumber"&gt;
		 *                               &lt;simpleType&gt;
		 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
		 *                                 &lt;/restriction&gt;
		 *                               &lt;/simpleType&gt;
		 *                             &lt;/element&gt;
		 *                             &lt;element name="MfrPartNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *                             &lt;element name="NeweggItemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *                             &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
		 *                             &lt;element name="ReturnQuantity"&gt;
		 *                               &lt;simpleType&gt;
		 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
		 *                                   &lt;minInclusive value="1"/&gt;
		 *                                 &lt;/restriction&gt;
		 *                               &lt;/simpleType&gt;
		 *                             &lt;/element&gt;
		 *                             &lt;element name="ReturnUnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
		 *                             &lt;element name="RefundShippingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
		 *                             &lt;element name="ShippedBy" minOccurs="0"&gt;
		 *                               &lt;simpleType&gt;
		 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
		 *                                   &lt;enumeration value="0"/&gt;
		 *                                   &lt;enumeration value="1"/&gt;
		 *                                 &lt;/restriction&gt;
		 *                               &lt;/simpleType&gt;
		 *                             &lt;/element&gt;
		 *                             &lt;element name="RefundShipppingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
		 *                             &lt;element name="RMAReason"&gt;
		 *                               &lt;simpleType&gt;
		 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
		 *                                   &lt;minInclusive value="1"/&gt;
		 *                                   &lt;maxInclusive value="9"/&gt;
		 *                                 &lt;/restriction&gt;
		 *                               &lt;/simpleType&gt;
		 *                             &lt;/element&gt;
		 *                             &lt;element name="RMAReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
		 *                           &lt;/all&gt;
		 *                         &lt;/restriction&gt;
		 *                       &lt;/complexContent&gt;
		 *                     &lt;/complexType&gt;
		 *                   &lt;/element&gt;
		 *                 &lt;/sequence&gt;
		 *               &lt;/restriction&gt;
		 *             &lt;/complexContent&gt;
		 *           &lt;/complexType&gt;
		 *         &lt;/element&gt;
		 *       &lt;/all&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {

		})
		public static class RMAInfo {

			@XmlElement(name = "RMANumber")
			@JsonProperty("RMANumber")
			private Integer rmaNumber;

			@XmlElement(name = "RMAType")
			@JsonProperty("RMAType")
			private int rmaType;

			@XmlElement(name = "RMATypeDescription", required = true)
			@JsonProperty("RMATypeDescription")
			private String rmaTypeDescription;

			@XmlElement(name = "SellerRMANumber", required = true)
			@JsonProperty("SellerRMANumber")
			private String sellerRMANumber;

			@XmlElement(name = "IssueUser", required = true)
			@JsonProperty("IssueUser")
			private String issueUser;

			@XmlElement(name = "RMADate", required = true)
			@JsonProperty("RMADate")
			private String rmaDate;

			@XmlElement(name = "RMAStatus", required = true)
			@JsonProperty("RMAStatus")
			private BigInteger rmaStatus;

			@XmlElement(name = "RMAStatusDescription", required = true)
			@JsonProperty("RMAStatusDescription")
			private String rmaStatusDescription;

			@XmlElement(name = "RMAShipMethod")
			@JsonProperty("RMAShipMethod")
			private String rmaShipMethod;

			@XmlElement(name = "RMAShipMethodDescription")
			@JsonProperty("RMAShipMethodDescription")
			private String rmaShipMethodDescription;

			@XmlElement(name = "OrderNumber")
			@JsonProperty("OrderNumber")
			private int orderNumber;

			@XmlElement(name = "OrderDate", required = true)
			@JsonProperty("OrderDate")
			private String orderDate;

			@XmlElement(name = "InvoiceNumber", required = true)
			@JsonProperty("InvoiceNumber")
			private BigInteger invoiceNumber;

			@XmlElement(name = "OrderAmount", required = true)
			@JsonProperty("OrderAmount")
			private BigDecimal orderAmount;

			@XmlElement(name = "AvailableRefundAmount", required = true)
			@JsonProperty("AvailableRefundAmount")
			private BigDecimal availableRefundAmount;

			@XmlElement(name = "RMAProcessedBy")
			@JsonProperty("RMAProcessedBy")
			private String rmaProcessedBy;

			@XmlElement(name = "RMAReceiveDate", required = true)
			@JsonProperty("RMAReceiveDate")
			private String rmaReceiveDate;

			@XmlElement(name = "RMANote")
			@JsonProperty("RMANote")
			private String rmaNote;

			@XmlElement(name = "PriorRefundAmount", required = true)
			@JsonProperty("PriorRefundAmount")
			private BigDecimal priorRefundAmount;

			@XmlElement(name = "CustomerName", required = true)
			@JsonProperty("CustomerName")
			private String customerName;

			@XmlElement(name = "CustomerPhoneNumber", required = true)
			@JsonProperty("CustomerPhoneNumber")
			private String customerPhoneNumber;

			@XmlElement(name = "CustomerEmailAddress", required = true)
			@JsonProperty("CustomerEmailAddress")
			private String customerEmailAddress;

			@XmlElement(name = "ShipToAddress1", required = true)
			@JsonProperty("ShipToAddress1")
			private String shipToAddress1;

			@XmlElement(name = "ShipToAddress2", required = true)
			@JsonProperty("ShipToAddress2")
			private String shipToAddress2;

			@XmlElement(name = "ShipToCityName", required = true)
			@JsonProperty("ShipToCityName")
			private String shipToCityName;

			@XmlElement(name = "ShipToStateCode", required = true)
			@JsonProperty("ShipToStateCode")
			private String shipToStateCode;

			@XmlElement(name = "ShipToZipCode", required = true)
			@JsonProperty("ShipToZipCode")
			private String shipToZipCode;

			@XmlElement(name = "ShipToLastName", required = true)
			@JsonProperty("ShipToLastName")
			private String shipToLastName;

			@XmlElement(name = "ShipToFirstName", required = true)
			@JsonProperty("ShipToFirstName")
			private String shipToFirstName;

			@XmlElement(name = "ShipToCompany", required = true)
			@JsonProperty("ShipToCompany")
			private String shipToCompany;

			@XmlElement(name = "RMATransactionList", required = true)
			@JsonProperty("RMATransactionList")
			private SubmitRMAResponse.ResponseBody.RMAInfo.RMATransactionList rmaTransactionList;

			public Integer getRmaNumber() {
				return rmaNumber;
			}

			public void setRmaNumber(Integer rmaNumber) {
				this.rmaNumber = rmaNumber;
			}

			public int getRmaType() {
				return rmaType;
			}

			public void setRmaType(int rmaType) {
				this.rmaType = rmaType;
			}

			public String getRmaTypeDescription() {
				return rmaTypeDescription;
			}

			public void setRmaTypeDescription(String rmaTypeDescription) {
				this.rmaTypeDescription = rmaTypeDescription;
			}

			public String getSellerRMANumber() {
				return sellerRMANumber;
			}

			public void setSellerRMANumber(String sellerRMANumber) {
				this.sellerRMANumber = sellerRMANumber;
			}

			public String getIssueUser() {
				return issueUser;
			}

			public void setIssueUser(String issueUser) {
				this.issueUser = issueUser;
			}

			public String getRmaDate() {
				return rmaDate;
			}

			public void setRmaDate(String rmaDate) {
				this.rmaDate = rmaDate;
			}

			public BigInteger getRmaStatus() {
				return rmaStatus;
			}

			public void setRmaStatus(BigInteger rmaStatus) {
				this.rmaStatus = rmaStatus;
			}

			public String getRmaStatusDescription() {
				return rmaStatusDescription;
			}

			public void setRmaStatusDescription(String rmaStatusDescription) {
				this.rmaStatusDescription = rmaStatusDescription;
			}

			public String getRmaShipMethod() {
				return rmaShipMethod;
			}

			public void setRmaShipMethod(String rmaShipMethod) {
				this.rmaShipMethod = rmaShipMethod;
			}

			public String getRmaShipMethodDescription() {
				return rmaShipMethodDescription;
			}

			public void setRmaShipMethodDescription(String rmaShipMethodDescription) {
				this.rmaShipMethodDescription = rmaShipMethodDescription;
			}

			public int getOrderNumber() {
				return orderNumber;
			}

			public void setOrderNumber(int orderNumber) {
				this.orderNumber = orderNumber;
			}

			public String getOrderDate() {
				return orderDate;
			}

			public void setOrderDate(String orderDate) {
				this.orderDate = orderDate;
			}

			public BigInteger getInvoiceNumber() {
				return invoiceNumber;
			}

			public void setInvoiceNumber(BigInteger invoiceNumber) {
				this.invoiceNumber = invoiceNumber;
			}

			public BigDecimal getOrderAmount() {
				return orderAmount;
			}

			public void setOrderAmount(BigDecimal orderAmount) {
				this.orderAmount = orderAmount;
			}

			public BigDecimal getAvailableRefundAmount() {
				return availableRefundAmount;
			}

			public void setAvailableRefundAmount(BigDecimal availableRefundAmount) {
				this.availableRefundAmount = availableRefundAmount;
			}

			public String getRmaProcessedBy() {
				return rmaProcessedBy;
			}

			public void setRmaProcessedBy(String rmaProcessedBy) {
				this.rmaProcessedBy = rmaProcessedBy;
			}

			public String getRmaReceiveDate() {
				return rmaReceiveDate;
			}

			public void setRmaReceiveDate(String rmaReceiveDate) {
				this.rmaReceiveDate = rmaReceiveDate;
			}

			public String getRmaNote() {
				return rmaNote;
			}

			public void setRmaNote(String rmaNote) {
				this.rmaNote = rmaNote;
			}

			public BigDecimal getPriorRefundAmount() {
				return priorRefundAmount;
			}

			public void setPriorRefundAmount(BigDecimal priorRefundAmount) {
				this.priorRefundAmount = priorRefundAmount;
			}

			public String getCustomerName() {
				return customerName;
			}

			public void setCustomerName(String customerName) {
				this.customerName = customerName;
			}

			public String getCustomerPhoneNumber() {
				return customerPhoneNumber;
			}

			public void setCustomerPhoneNumber(String customerPhoneNumber) {
				this.customerPhoneNumber = customerPhoneNumber;
			}

			public String getCustomerEmailAddress() {
				return customerEmailAddress;
			}

			public void setCustomerEmailAddress(String customerEmailAddress) {
				this.customerEmailAddress = customerEmailAddress;
			}

			public String getShipToAddress1() {
				return shipToAddress1;
			}

			public void setShipToAddress1(String shipToAddress1) {
				this.shipToAddress1 = shipToAddress1;
			}

			public String getShipToAddress2() {
				return shipToAddress2;
			}

			public void setShipToAddress2(String shipToAddress2) {
				this.shipToAddress2 = shipToAddress2;
			}

			public String getShipToCityName() {
				return shipToCityName;
			}

			public void setShipToCityName(String shipToCityName) {
				this.shipToCityName = shipToCityName;
			}

			public String getShipToStateCode() {
				return shipToStateCode;
			}

			public void setShipToStateCode(String shipToStateCode) {
				this.shipToStateCode = shipToStateCode;
			}

			public String getShipToZipCode() {
				return shipToZipCode;
			}

			public void setShipToZipCode(String shipToZipCode) {
				this.shipToZipCode = shipToZipCode;
			}

			public String getShipToLastName() {
				return shipToLastName;
			}

			public void setShipToLastName(String shipToLastName) {
				this.shipToLastName = shipToLastName;
			}

			public String getShipToFirstName() {
				return shipToFirstName;
			}

			public void setShipToFirstName(String shipToFirstName) {
				this.shipToFirstName = shipToFirstName;
			}

			public String getShipToCompany() {
				return shipToCompany;
			}

			public void setShipToCompany(String shipToCompany) {
				this.shipToCompany = shipToCompany;
			}

			public SubmitRMAResponse.ResponseBody.RMAInfo.RMATransactionList getRmaTransactionList() {
				return rmaTransactionList;
			}

			public void setRmaTransactionList(SubmitRMAResponse.ResponseBody.RMAInfo.RMATransactionList rmaTransactionList) {
				this.rmaTransactionList = rmaTransactionList;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType&gt;
			 *   &lt;complexContent&gt;
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
			 *       &lt;sequence maxOccurs="unbounded"&gt;
			 *         &lt;element name="RMATransaction"&gt;
			 *           &lt;complexType&gt;
			 *             &lt;complexContent&gt;
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
			 *                 &lt;all&gt;
			 *                   &lt;element name="SellerPartNumber"&gt;
			 *                     &lt;simpleType&gt;
			 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
			 *                       &lt;/restriction&gt;
			 *                     &lt;/simpleType&gt;
			 *                   &lt;/element&gt;
			 *                   &lt;element name="MfrPartNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
			 *                   &lt;element name="NeweggItemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
			 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
			 *                   &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
			 *                   &lt;element name="ReturnQuantity"&gt;
			 *                     &lt;simpleType&gt;
			 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
			 *                         &lt;minInclusive value="1"/&gt;
			 *                       &lt;/restriction&gt;
			 *                     &lt;/simpleType&gt;
			 *                   &lt;/element&gt;
			 *                   &lt;element name="ReturnUnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
			 *                   &lt;element name="RefundShippingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
			 *                   &lt;element name="ShippedBy" minOccurs="0"&gt;
			 *                     &lt;simpleType&gt;
			 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
			 *                         &lt;enumeration value="0"/&gt;
			 *                         &lt;enumeration value="1"/&gt;
			 *                       &lt;/restriction&gt;
			 *                     &lt;/simpleType&gt;
			 *                   &lt;/element&gt;
			 *                   &lt;element name="RefundShipppingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
			 *                   &lt;element name="RMAReason"&gt;
			 *                     &lt;simpleType&gt;
			 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
			 *                         &lt;minInclusive value="1"/&gt;
			 *                         &lt;maxInclusive value="9"/&gt;
			 *                       &lt;/restriction&gt;
			 *                     &lt;/simpleType&gt;
			 *                   &lt;/element&gt;
			 *                   &lt;element name="RMAReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
			 *                 &lt;/all&gt;
			 *               &lt;/restriction&gt;
			 *             &lt;/complexContent&gt;
			 *           &lt;/complexType&gt;
			 *         &lt;/element&gt;
			 *       &lt;/sequence&gt;
			 *     &lt;/restriction&gt;
			 *   &lt;/complexContent&gt;
			 * &lt;/complexType&gt;
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"rmaTransaction"
			})
			public static class RMATransactionList {

				@XmlElement(name = "RMATransaction", required = true)
				@JsonProperty("RMATransaction")
				private SubmitRMAResponse.ResponseBody.RMAInfo.RMATransactionList.RMATransaction rmaTransaction;

				/**
				 * Gets the value of the rmaTransaction property.
				 * 
				 * <p>
				 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the rmaTransaction property.
				 * 
				 * <p>
				 * For example, to add a new item, do as follows:
				 * 
				 * <pre>
				 * getRMATransaction().add(newItem);
				 * </pre>
				 * 
				 * @return
				 * Objects of the following type(s) are allowed in the list {@link SubmitRMAResponse.ResponseBody.RMAInfo.RMATransactionList.RMATransaction }
				 * 
				 * 
				 */				
				public SubmitRMAResponse.ResponseBody.RMAInfo.RMATransactionList.RMATransaction getRmaTransaction() {
					return rmaTransaction;
				}

				public void setRmaTransaction(SubmitRMAResponse.ResponseBody.RMAInfo.RMATransactionList.RMATransaction rmaTransaction) {
					this.rmaTransaction = rmaTransaction;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType&gt;
				 *   &lt;complexContent&gt;
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
				 *       &lt;all&gt;
				 *         &lt;element name="SellerPartNumber"&gt;
				 *           &lt;simpleType&gt;
				 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
				 *             &lt;/restriction&gt;
				 *           &lt;/simpleType&gt;
				 *         &lt;/element&gt;
				 *         &lt;element name="MfrPartNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
				 *         &lt;element name="NeweggItemNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
				 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
				 *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
				 *         &lt;element name="ReturnQuantity"&gt;
				 *           &lt;simpleType&gt;
				 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
				 *               &lt;minInclusive value="1"/&gt;
				 *             &lt;/restriction&gt;
				 *           &lt;/simpleType&gt;
				 *         &lt;/element&gt;
				 *         &lt;element name="ReturnUnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
				 *         &lt;element name="RefundShippingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
				 *         &lt;element name="ShippedBy" minOccurs="0"&gt;
				 *           &lt;simpleType&gt;
				 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
				 *               &lt;enumeration value="0"/&gt;
				 *               &lt;enumeration value="1"/&gt;
				 *             &lt;/restriction&gt;
				 *           &lt;/simpleType&gt;
				 *         &lt;/element&gt;
				 *         &lt;element name="RefundShipppingPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
				 *         &lt;element name="RMAReason"&gt;
				 *           &lt;simpleType&gt;
				 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
				 *               &lt;minInclusive value="1"/&gt;
				 *               &lt;maxInclusive value="9"/&gt;
				 *             &lt;/restriction&gt;
				 *           &lt;/simpleType&gt;
				 *         &lt;/element&gt;
				 *         &lt;element name="RMAReasonDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
				 *       &lt;/all&gt;
				 *     &lt;/restriction&gt;
				 *   &lt;/complexContent&gt;
				 * &lt;/complexType&gt;
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = {

				})
				public static class RMATransaction {

					@XmlElement(name = "SellerPartNumber", required = true)
					@JsonProperty("SellerPartNumber")
					private String sellerPartNumber;

					@XmlElement(name = "MfrPartNumber", required = true)
					@JsonProperty("MfrPartNumber")
					private String mfrPartNumber;

					@XmlElement(name = "NeweggItemNumber", required = true)
					@JsonProperty("NeweggItemNumber")
					private String neweggItemNumber;

					@XmlElement(name = "Description", required = true)
					@JsonProperty("Description")
					private String description;

					@XmlElement(name = "UnitPrice", required = true)
					@JsonProperty("UnitPrice")
					private BigDecimal unitPrice;

					@XmlElement(name = "ReturnQuantity", required = true)
					@JsonProperty("ReturnQuantity")
					private BigInteger returnQuantity;

					@XmlElement(name = "ReturnUnitPrice")
					@JsonProperty("ReturnUnitPrice")
					private BigDecimal returnUnitPrice;

					@XmlElement(name = "RefundShippingPrice", required = true)
					@JsonProperty("RefundShippingPrice")
					private BigDecimal refundShippingPrice;

					@XmlElement(name = "ShippedBy")
					@JsonProperty("ShippedBy")
					private Integer shippedBy;

					@XmlElement(name = "RefundShipppingPrice")
					@JsonProperty("RefundShipppingPrice")
					private BigDecimal refundShipppingPrice;

					@XmlElement(name = "RMAReason")
					@JsonProperty("RMAReason")
					private int rmaReason;

					@XmlElement(name = "RMAReasonDescription", required = true)
					@JsonProperty("RMAReasonDescription")
					private String rmaReasonDescription;

					public String getSellerPartNumber() {
						return sellerPartNumber;
					}

					public void setSellerPartNumber(String sellerPartNumber) {
						this.sellerPartNumber = sellerPartNumber;
					}

					public String getMfrPartNumber() {
						return mfrPartNumber;
					}

					public void setMfrPartNumber(String mfrPartNumber) {
						this.mfrPartNumber = mfrPartNumber;
					}

					public String getNeweggItemNumber() {
						return neweggItemNumber;
					}

					public void setNeweggItemNumber(String neweggItemNumber) {
						this.neweggItemNumber = neweggItemNumber;
					}

					public String getDescription() {
						return description;
					}

					public void setDescription(String description) {
						this.description = description;
					}

					public BigDecimal getUnitPrice() {
						return unitPrice;
					}

					public void setUnitPrice(BigDecimal unitPrice) {
						this.unitPrice = unitPrice;
					}

					public BigInteger getReturnQuantity() {
						return returnQuantity;
					}

					public void setReturnQuantity(BigInteger returnQuantity) {
						this.returnQuantity = returnQuantity;
					}

					public BigDecimal getReturnUnitPrice() {
						return returnUnitPrice;
					}

					public void setReturnUnitPrice(BigDecimal returnUnitPrice) {
						this.returnUnitPrice = returnUnitPrice;
					}

					public BigDecimal getRefundShippingPrice() {
						return refundShippingPrice;
					}

					public void setRefundShippingPrice(BigDecimal refundShippingPrice) {
						this.refundShippingPrice = refundShippingPrice;
					}

					public Integer getShippedBy() {
						return shippedBy;
					}

					public void setShippedBy(Integer shippedBy) {
						this.shippedBy = shippedBy;
					}

					public BigDecimal getRefundShipppingPrice() {
						return refundShipppingPrice;
					}

					public void setRefundShipppingPrice(BigDecimal refundShipppingPrice) {
						this.refundShipppingPrice = refundShipppingPrice;
					}

					public int getRmaReason() {
						return rmaReason;
					}

					public void setRmaReason(int rmaReason) {
						this.rmaReason = rmaReason;
					}

					public String getRmaReasonDescription() {
						return rmaReasonDescription;
					}

					public void setRmaReasonDescription(String rmaReasonDescription) {
						this.rmaReasonDescription = rmaReasonDescription;
					}

				}

			}

		}

	}

}
