//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.13 at 09:20:21 AM CST 
//


package com.newegg.marketplace.sdk.datafeed.model.sub.properties;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GuitarsBrandValueList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;simpleType name="GuitarsBrandValueList"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Silvertone"/&gt;
 *     &lt;enumeration value="eMedia"/&gt;
 *     &lt;enumeration value="Samson"/&gt;
 *     &lt;enumeration value="Vox"/&gt;
 *     &lt;enumeration value="Korg"/&gt;
 *     &lt;enumeration value="Peavey"/&gt;
 *     &lt;enumeration value="Casio"/&gt;
 *     &lt;enumeration value="Behringer"/&gt;
 *     &lt;enumeration value="Stagg"/&gt;
 *     &lt;enumeration value="Bryant"/&gt;
 *     &lt;enumeration value="Pyle"/&gt;
 *     &lt;enumeration value="Zoom"/&gt;
 *     &lt;enumeration value="Spectrum"/&gt;
 *     &lt;enumeration value="Epiphone"/&gt;
 *     &lt;enumeration value="Arcadia"/&gt;
 *     &lt;enumeration value="PylePro"/&gt;
 *     &lt;enumeration value="Nady"/&gt;
 *     &lt;enumeration value="Fretlight"/&gt;
 *     &lt;enumeration value="IK Multimedia"/&gt;
 *     &lt;enumeration value="Audiovox"/&gt;
 *     &lt;enumeration value="Fender"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GuitarsBrandValueList")
@XmlEnum
public enum GuitarsBrandValueList {

    @XmlEnumValue("Silvertone")
    SILVERTONE("Silvertone"),
    @XmlEnumValue("eMedia")
    E_MEDIA("eMedia"),
    @XmlEnumValue("Samson")
    SAMSON("Samson"),
    @XmlEnumValue("Vox")
    VOX("Vox"),
    @XmlEnumValue("Korg")
    KORG("Korg"),
    @XmlEnumValue("Peavey")
    PEAVEY("Peavey"),
    @XmlEnumValue("Casio")
    CASIO("Casio"),
    @XmlEnumValue("Behringer")
    BEHRINGER("Behringer"),
    @XmlEnumValue("Stagg")
    STAGG("Stagg"),
    @XmlEnumValue("Bryant")
    BRYANT("Bryant"),
    @XmlEnumValue("Pyle")
    PYLE("Pyle"),
    @XmlEnumValue("Zoom")
    ZOOM("Zoom"),
    @XmlEnumValue("Spectrum")
    SPECTRUM("Spectrum"),
    @XmlEnumValue("Epiphone")
    EPIPHONE("Epiphone"),
    @XmlEnumValue("Arcadia")
    ARCADIA("Arcadia"),
    @XmlEnumValue("PylePro")
    PYLE_PRO("PylePro"),
    @XmlEnumValue("Nady")
    NADY("Nady"),
    @XmlEnumValue("Fretlight")
    FRETLIGHT("Fretlight"),
    @XmlEnumValue("IK Multimedia")
    IK_MULTIMEDIA("IK Multimedia"),
    @XmlEnumValue("Audiovox")
    AUDIOVOX("Audiovox"),
    @XmlEnumValue("Fender")
    FENDER("Fender");
    private final String value;

    GuitarsBrandValueList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GuitarsBrandValueList fromValue(String v) {
        for (GuitarsBrandValueList c: GuitarsBrandValueList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
