//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.12 at 02:15:02 PM CST 
//


package com.newegg.marketplace.sdk.datafeed.model.sub.properties;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeadsetSeriesValueList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HeadsetSeriesValueList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Upgrader Series"/>
 *     &lt;enumeration value="Classic Series"/>
 *     &lt;enumeration value="MUZX Series"/>
 *     &lt;enumeration value="Sports Series"/>
 *     &lt;enumeration value="TuneBuds Mobile"/>
 *     &lt;enumeration value="Full Metal Jacket"/>
 *     &lt;enumeration value="IMAGE S4-WHITE"/>
 *     &lt;enumeration value="IMAGE S4i White"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HeadsetSeriesValueList")
@XmlEnum
public enum HeadsetSeriesValueList {

    @XmlEnumValue("Upgrader Series")
    UPGRADER_SERIES("Upgrader Series"),
    @XmlEnumValue("Classic Series")
    CLASSIC_SERIES("Classic Series"),
    @XmlEnumValue("MUZX Series")
    MUZX_SERIES("MUZX Series"),
    @XmlEnumValue("Sports Series")
    SPORTS_SERIES("Sports Series"),
    @XmlEnumValue("TuneBuds Mobile")
    TUNE_BUDS_MOBILE("TuneBuds Mobile"),
    @XmlEnumValue("Full Metal Jacket")
    FULL_METAL_JACKET("Full Metal Jacket"),
    @XmlEnumValue("IMAGE S4-WHITE")
    IMAGE_S_4_WHITE("IMAGE S4-WHITE"),
    @XmlEnumValue("IMAGE S4i White")
    IMAGE_S_4_I_WHITE("IMAGE S4i White");
    private final String value;

    HeadsetSeriesValueList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HeadsetSeriesValueList fromValue(String v) {
        for (HeadsetSeriesValueList c: HeadsetSeriesValueList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
