//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.20 at 03:45:10 PM CST 
//


package com.newegg.marketplace.sdk.seller.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="IsSuccess"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="true"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OperationType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="GetSellerSubcategoryResponse"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SellerID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ResponseBody"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SubcategoryList"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Subcategory" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;all&gt;
 *                                       &lt;element name="IndustryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="IndustryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Enabled"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                             &lt;minInclusive value="0"/&gt;
 *                                             &lt;maxInclusive value="1"/&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/all&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "NeweggAPIResponse")
public class GetSubcategoryStatusResponse {

    @XmlElement(name = "IsSuccess", required = true)
    @JsonProperty("IsSuccess")
    protected boolean isSuccess;
    @XmlElement(name = "OperationType", required = true)
    @JsonProperty("OperationType")
    protected String operationType = "GetSellerSubcategoryResponse";
    @XmlElement(name = "SellerID", required = true)
    @JsonProperty("SellerID")
    protected String sellerID;
    @XmlElement(name = "ResponseBody", required = true)
    @JsonProperty("ResponseBody")
    protected GetSubcategoryStatusResponse.ResponseBody responseBody;

    /**
     * Gets the value of the isSuccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public boolean getIsSuccess() {
        return isSuccess;
    }

    /**
     * Sets the value of the isSuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSuccess(boolean value) {
        this.isSuccess = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the sellerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerID() {
        return sellerID;
    }

    /**
     * Sets the value of the sellerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerID(String value) {
        this.sellerID = value;
    }

    /**
     * Gets the value of the responseBody property.
     * 
     * @return
     *     possible object is
     *     {@link GetSubcategoryStatusResponse.ResponseBody }
     *     
     */
    public GetSubcategoryStatusResponse.ResponseBody getResponseBody() {
        return responseBody;
    }

    /**
     * Sets the value of the responseBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetSubcategoryStatusResponse.ResponseBody }
     *     
     */
    public void setResponseBody(GetSubcategoryStatusResponse.ResponseBody value) {
        this.responseBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SubcategoryList"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Subcategory" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;all&gt;
     *                             &lt;element name="IndustryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="IndustryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Enabled"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                                   &lt;minInclusive value="0"/&gt;
     *                                   &lt;maxInclusive value="1"/&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/all&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subcategoryList"
    })
    public static class ResponseBody {

        @XmlElement(name = "SubcategoryList", required = true)
        //@JsonProperty("SubcategoryList")
        @JsonUnwrapped
        protected GetSubcategoryStatusResponse.ResponseBody.SubcategoryList subcategoryList;

        /**
         * Gets the value of the subcategoryList property.
         * 
         * @return
         *     possible object is
         *     {@link GetSubcategoryStatusResponse.ResponseBody.SubcategoryList }
         *     
         */
        public GetSubcategoryStatusResponse.ResponseBody.SubcategoryList getSubcategoryList() {
            return subcategoryList;
        }

        /**
         * Sets the value of the subcategoryList property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetSubcategoryStatusResponse.ResponseBody.SubcategoryList }
         *     
         */
        public void setSubcategoryList(GetSubcategoryStatusResponse.ResponseBody.SubcategoryList value) {
            this.subcategoryList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Subcategory" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;all&gt;
         *                   &lt;element name="IndustryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="IndustryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Enabled"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *                         &lt;minInclusive value="0"/&gt;
         *                         &lt;maxInclusive value="1"/&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/all&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subcategory"
        })
        public static class SubcategoryList {

            @XmlElement(name = "Subcategory", required = true)
            @JsonProperty("SubcategoryList")
            protected List<GetSubcategoryStatusResponse.ResponseBody.SubcategoryList.Subcategory> subcategory;

            /**
             * Gets the value of the subcategory property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the subcategory property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSubcategory().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GetSubcategoryStatusResponse.ResponseBody.SubcategoryList.Subcategory }
             * 
             * @return
             * Objects of the following type(s) are allowed in the list
             * {@link GetSubcategoryStatusResponse.ResponseBody.SubcategoryList.Subcategory }
             * 
             */
            public List<GetSubcategoryStatusResponse.ResponseBody.SubcategoryList.Subcategory> getSubcategory() {
                if (subcategory == null) {
                    subcategory = new ArrayList<GetSubcategoryStatusResponse.ResponseBody.SubcategoryList.Subcategory>();
                }
                return this.subcategory;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;all&gt;
             *         &lt;element name="IndustryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="IndustryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Enabled"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
             *               &lt;minInclusive value="0"/&gt;
             *               &lt;maxInclusive value="1"/&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *       &lt;/all&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class Subcategory {

                @XmlElement(name = "IndustryCode", required = true)
                @JsonProperty("IndustryCode")
                protected String industryCode;
                @XmlElement(name = "IndustryName", required = true)
                @JsonProperty("IndustryName")
                protected String industryName;
                @XmlElement(name = "SubcategoryID")
                @JsonProperty("SubcategoryID")
                protected int subcategoryID;
                @XmlElement(name = "SubcategoryName", required = true)
                @JsonProperty("SubcategoryName")
                protected String subcategoryName;
                @XmlElement(name = "Enabled")
                @JsonProperty("Enabled")
                protected int enabled;

                /**
                 * Gets the value of the industryCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIndustryCode() {
                    return industryCode;
                }

                /**
                 * Sets the value of the industryCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIndustryCode(String value) {
                    this.industryCode = value;
                }

                /**
                 * Gets the value of the industryName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIndustryName() {
                    return industryName;
                }

                /**
                 * Sets the value of the industryName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIndustryName(String value) {
                    this.industryName = value;
                }

                /**
                 * Gets the value of the subcategoryID property.
                 * @return
                 * possible object is 
                 *     {@link int }
                 * 
                 */
                public int getSubcategoryID() {
                    return subcategoryID;
                }

                /**
                 * Sets the value of the subcategoryID property.
                 * @param value
                 *     allowed object is
                 *     {@link  }
                 * 
                 */
                public void setSubcategoryID(int value) {
                    this.subcategoryID = value;
                }

                /**
                 * Gets the value of the subcategoryName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSubcategoryName() {
                    return subcategoryName;
                }

                /**
                 * Sets the value of the subcategoryName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSubcategoryName(String value) {
                    this.subcategoryName = value;
                }

                /**
                 * Gets the value of the enabled property.
                 * @return
                 * possible object is 
                 *     {@link int }
                 * 
                 */
                public int getEnabled() {
                    return enabled;
                }

                /**
                 * Sets the value of the enabled property.
                 * @param value
                 *     allowed object is
                 *     {@link  }
                 * 
                 */
                public void setEnabled(int value) {
                    this.enabled = value;
                }

            }

        }

    }

}
