//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.21 at 04:41:48 PM CST 
//


package com.newegg.marketplace.sdk.item.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Condition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Value">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CountryList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CountryCode" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="AUS"/>
 *                         &lt;enumeration value="NZL"/>
 *                         &lt;enumeration value="GBR"/>
 *                         &lt;enumeration value="IRL"/>
 *                         &lt;enumeration value="NLD"/>
 *                         &lt;enumeration value="POL"/>
 *                         &lt;enumeration value="IND"/>
 *                         &lt;enumeration value="SGP"/>
 *                         &lt;enumeration value="USA"/>
 *                         &lt;enumeration value="HKG"/>
 *                         &lt;enumeration value="MAC"/>
 *                         &lt;enumeration value="IDN"/>
 *                         &lt;enumeration value="PHL"/>
 *                         &lt;enumeration value="KOR"/>
 *                         &lt;enumeration value="THA"/>
 *                         &lt;enumeration value="BRA"/>
 *                         &lt;enumeration value="CHL"/>
 *                         &lt;enumeration value="CHN"/>
 *                         &lt;enumeration value="COL"/>
 *                         &lt;enumeration value="CRI"/>
 *                         &lt;enumeration value="DOM"/>
 *                         &lt;enumeration value="ECU"/>
 *                         &lt;enumeration value="SLV"/>
 *                         &lt;enumeration value="GTM"/>
 *                         &lt;enumeration value="HND"/>
 *                         &lt;enumeration value="JAM"/>
 *                         &lt;enumeration value="MEX"/>
 *                         &lt;enumeration value="NIC"/>
 *                         &lt;enumeration value="PAN"/>
 *                         &lt;enumeration value="ISR"/>
 *                         &lt;enumeration value="SAU"/>
 *                         &lt;enumeration value="TUR"/>
 *                         &lt;enumeration value="ARE"/>
 *                         &lt;enumeration value="AUT"/>
 *                         &lt;enumeration value="BEL"/>
 *                         &lt;enumeration value="BGR"/>
 *                         &lt;enumeration value="DNK"/>
 *                         &lt;enumeration value="FIN"/>
 *                         &lt;enumeration value="FRA"/>
 *                         &lt;enumeration value="DEU"/>
 *                         &lt;enumeration value="GRC"/>
 *                         &lt;enumeration value="HUN"/>
 *                         &lt;enumeration value="ITA"/>
 *                         &lt;enumeration value="LVA"/>
 *                         &lt;enumeration value="LUX"/>
 *                         &lt;enumeration value="MCO"/>
 *                         &lt;enumeration value="NOR"/>
 *                         &lt;enumeration value="PRT"/>
 *                         &lt;enumeration value="SVK"/>
 *                         &lt;enumeration value="SVN"/>
 *                         &lt;enumeration value="ESP"/>
 *                         &lt;enumeration value="SWE"/>
 *                         &lt;enumeration value="CHE"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ContentQueryCriteria")
public class GetInternationalItemPriceRequest {

    @XmlElement(name = "Condition", defaultValue = "1")
    @JsonProperty("Quantity")
    protected Integer condition;
    @XmlElement(name = "Type")
    @JsonProperty("Type")
    protected int type;
    @XmlElement(name = "Value", required = true)
    @JsonProperty("Value")
    protected String value;
    @XmlElement(name = "CountryList")
    @JsonProperty("CountryList")
    protected GetInternationalItemPriceRequest.CountryList countryList;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCondition(Integer value) {
        this.condition = value;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(int value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the countryList property.
     * 
     * @return
     *     possible object is
     *     {@link GetInternationalItemPriceRequest.CountryList }
     *     
     */
    public GetInternationalItemPriceRequest.CountryList getCountryList() {
        return countryList;
    }

    /**
     * Sets the value of the countryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetInternationalItemPriceRequest.CountryList }
     *     
     */
    public void setCountryList(GetInternationalItemPriceRequest.CountryList value) {
        this.countryList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CountryCode" maxOccurs="unbounded">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="AUS"/>
     *               &lt;enumeration value="NZL"/>
     *               &lt;enumeration value="GBR"/>
     *               &lt;enumeration value="IRL"/>
     *               &lt;enumeration value="NLD"/>
     *               &lt;enumeration value="POL"/>
     *               &lt;enumeration value="IND"/>
     *               &lt;enumeration value="SGP"/>
     *               &lt;enumeration value="USA"/>
     *               &lt;enumeration value="HKG"/>
     *               &lt;enumeration value="MAC"/>
     *               &lt;enumeration value="IDN"/>
     *               &lt;enumeration value="PHL"/>
     *               &lt;enumeration value="KOR"/>
     *               &lt;enumeration value="THA"/>
     *               &lt;enumeration value="BRA"/>
     *               &lt;enumeration value="CHL"/>
     *               &lt;enumeration value="CHN"/>
     *               &lt;enumeration value="COL"/>
     *               &lt;enumeration value="CRI"/>
     *               &lt;enumeration value="DOM"/>
     *               &lt;enumeration value="ECU"/>
     *               &lt;enumeration value="SLV"/>
     *               &lt;enumeration value="GTM"/>
     *               &lt;enumeration value="HND"/>
     *               &lt;enumeration value="JAM"/>
     *               &lt;enumeration value="MEX"/>
     *               &lt;enumeration value="NIC"/>
     *               &lt;enumeration value="PAN"/>
     *               &lt;enumeration value="ISR"/>
     *               &lt;enumeration value="SAU"/>
     *               &lt;enumeration value="TUR"/>
     *               &lt;enumeration value="ARE"/>
     *               &lt;enumeration value="AUT"/>
     *               &lt;enumeration value="BEL"/>
     *               &lt;enumeration value="BGR"/>
     *               &lt;enumeration value="DNK"/>
     *               &lt;enumeration value="FIN"/>
     *               &lt;enumeration value="FRA"/>
     *               &lt;enumeration value="DEU"/>
     *               &lt;enumeration value="GRC"/>
     *               &lt;enumeration value="HUN"/>
     *               &lt;enumeration value="ITA"/>
     *               &lt;enumeration value="LVA"/>
     *               &lt;enumeration value="LUX"/>
     *               &lt;enumeration value="MCO"/>
     *               &lt;enumeration value="NOR"/>
     *               &lt;enumeration value="PRT"/>
     *               &lt;enumeration value="SVK"/>
     *               &lt;enumeration value="SVN"/>
     *               &lt;enumeration value="ESP"/>
     *               &lt;enumeration value="SWE"/>
     *               &lt;enumeration value="CHE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "countryCode"
    })
    public static class CountryList {

        @XmlElement(name = "CountryCode", required = true)
        @JsonProperty("CountryCode")
        protected List<String> countryCode;

        /**
         * Gets the value of the countryCode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the countryCode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCountryCode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCountryCode() {
            if (countryCode == null) {
                countryCode = new ArrayList<String>();
            }
            return this.countryCode;
        }

    }

}
