//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.21 at 04:41:48 PM CST 
//

package com.newegg.marketplace.sdk.item.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Condition" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *               &lt;enumeration value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Type"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Value"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="40"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CountryList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CountryCode" maxOccurs="unbounded"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="AUS"/&gt;
 *                         &lt;enumeration value="NZL"/&gt;
 *                         &lt;enumeration value="GBR"/&gt;
 *                         &lt;enumeration value="IRL"/&gt;
 *                         &lt;enumeration value="NLD"/&gt;
 *                         &lt;enumeration value="POL"/&gt;
 *                         &lt;enumeration value="IND"/&gt;
 *                         &lt;enumeration value="SGP"/&gt;
 *                         &lt;enumeration value="USA"/&gt;
 *                         &lt;enumeration value="HKG"/&gt;
 *                         &lt;enumeration value="MAC"/&gt;
 *                         &lt;enumeration value="IDN"/&gt;
 *                         &lt;enumeration value="PHL"/&gt;
 *                         &lt;enumeration value="KOR"/&gt;
 *                         &lt;enumeration value="THA"/&gt;
 *                         &lt;enumeration value="BRA"/&gt;
 *                         &lt;enumeration value="CHL"/&gt;
 *                         &lt;enumeration value="CHN"/&gt;
 *                         &lt;enumeration value="COL"/&gt;
 *                         &lt;enumeration value="CRI"/&gt;
 *                         &lt;enumeration value="DOM"/&gt;
 *                         &lt;enumeration value="ECU"/&gt;
 *                         &lt;enumeration value="SLV"/&gt;
 *                         &lt;enumeration value="GTM"/&gt;
 *                         &lt;enumeration value="HND"/&gt;
 *                         &lt;enumeration value="JAM"/&gt;
 *                         &lt;enumeration value="MEX"/&gt;
 *                         &lt;enumeration value="NIC"/&gt;
 *                         &lt;enumeration value="PAN"/&gt;
 *                         &lt;enumeration value="ISR"/&gt;
 *                         &lt;enumeration value="SAU"/&gt;
 *                         &lt;enumeration value="TUR"/&gt;
 *                         &lt;enumeration value="ARE"/&gt;
 *                         &lt;enumeration value="AUT"/&gt;
 *                         &lt;enumeration value="BEL"/&gt;
 *                         &lt;enumeration value="BGR"/&gt;
 *                         &lt;enumeration value="DNK"/&gt;
 *                         &lt;enumeration value="FIN"/&gt;
 *                         &lt;enumeration value="FRA"/&gt;
 *                         &lt;enumeration value="DEU"/&gt;
 *                         &lt;enumeration value="GRC"/&gt;
 *                         &lt;enumeration value="HUN"/&gt;
 *                         &lt;enumeration value="ITA"/&gt;
 *                         &lt;enumeration value="LVA"/&gt;
 *                         &lt;enumeration value="LUX"/&gt;
 *                         &lt;enumeration value="MCO"/&gt;
 *                         &lt;enumeration value="NOR"/&gt;
 *                         &lt;enumeration value="PRT"/&gt;
 *                         &lt;enumeration value="SVK"/&gt;
 *                         &lt;enumeration value="SVN"/&gt;
 *                         &lt;enumeration value="ESP"/&gt;
 *                         &lt;enumeration value="SWE"/&gt;
 *                         &lt;enumeration value="CHE"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ContentQueryCriteria")
public class GetInternationalItemPriceRequest {

	@XmlElement(name = "Condition", defaultValue = "1")
	@JsonProperty("Quantity")
	protected Integer condition;
	@XmlElement(name = "Type")
	@JsonProperty("Type")
	protected int type;
	@XmlElement(name = "Value", required = true)
	@JsonProperty("Value")
	protected String value;
	@XmlElement(name = "CountryList")
	@JsonProperty("CountryList")
	protected GetInternationalItemPriceRequest.CountryList countryList;

	/**
	 * Gets the value of the condition property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCondition() {
		return condition;
	}

	/**
	 * Sets the value of the condition property.
	 * 
	 * @param value allowed object is {@link Integer }
	 * 
	 */
	public void setCondition(Integer value) {
		this.condition = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link int }
	 * 
	 */
	public int getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value allowed object is {@link }
	 * 
	 */
	public void setType(int value) {
		this.type = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the countryList property.
	 * 
	 * @return possible object is
	 *         {@link GetInternationalItemPriceRequest.CountryList }
	 * 
	 */
	public GetInternationalItemPriceRequest.CountryList getCountryList() {
		return countryList;
	}

	/**
	 * Sets the value of the countryList property.
	 * 
	 * @param value allowed object is
	 *              {@link GetInternationalItemPriceRequest.CountryList }
	 * 
	 */
	public void setCountryList(GetInternationalItemPriceRequest.CountryList value) {
		this.countryList = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="CountryCode" maxOccurs="unbounded"&gt;
	 *           &lt;simpleType&gt;
	 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
	 *               &lt;enumeration value="AUS"/&gt;
	 *               &lt;enumeration value="NZL"/&gt;
	 *               &lt;enumeration value="GBR"/&gt;
	 *               &lt;enumeration value="IRL"/&gt;
	 *               &lt;enumeration value="NLD"/&gt;
	 *               &lt;enumeration value="POL"/&gt;
	 *               &lt;enumeration value="IND"/&gt;
	 *               &lt;enumeration value="SGP"/&gt;
	 *               &lt;enumeration value="USA"/&gt;
	 *               &lt;enumeration value="HKG"/&gt;
	 *               &lt;enumeration value="MAC"/&gt;
	 *               &lt;enumeration value="IDN"/&gt;
	 *               &lt;enumeration value="PHL"/&gt;
	 *               &lt;enumeration value="KOR"/&gt;
	 *               &lt;enumeration value="THA"/&gt;
	 *               &lt;enumeration value="BRA"/&gt;
	 *               &lt;enumeration value="CHL"/&gt;
	 *               &lt;enumeration value="CHN"/&gt;
	 *               &lt;enumeration value="COL"/&gt;
	 *               &lt;enumeration value="CRI"/&gt;
	 *               &lt;enumeration value="DOM"/&gt;
	 *               &lt;enumeration value="ECU"/&gt;
	 *               &lt;enumeration value="SLV"/&gt;
	 *               &lt;enumeration value="GTM"/&gt;
	 *               &lt;enumeration value="HND"/&gt;
	 *               &lt;enumeration value="JAM"/&gt;
	 *               &lt;enumeration value="MEX"/&gt;
	 *               &lt;enumeration value="NIC"/&gt;
	 *               &lt;enumeration value="PAN"/&gt;
	 *               &lt;enumeration value="ISR"/&gt;
	 *               &lt;enumeration value="SAU"/&gt;
	 *               &lt;enumeration value="TUR"/&gt;
	 *               &lt;enumeration value="ARE"/&gt;
	 *               &lt;enumeration value="AUT"/&gt;
	 *               &lt;enumeration value="BEL"/&gt;
	 *               &lt;enumeration value="BGR"/&gt;
	 *               &lt;enumeration value="DNK"/&gt;
	 *               &lt;enumeration value="FIN"/&gt;
	 *               &lt;enumeration value="FRA"/&gt;
	 *               &lt;enumeration value="DEU"/&gt;
	 *               &lt;enumeration value="GRC"/&gt;
	 *               &lt;enumeration value="HUN"/&gt;
	 *               &lt;enumeration value="ITA"/&gt;
	 *               &lt;enumeration value="LVA"/&gt;
	 *               &lt;enumeration value="LUX"/&gt;
	 *               &lt;enumeration value="MCO"/&gt;
	 *               &lt;enumeration value="NOR"/&gt;
	 *               &lt;enumeration value="PRT"/&gt;
	 *               &lt;enumeration value="SVK"/&gt;
	 *               &lt;enumeration value="SVN"/&gt;
	 *               &lt;enumeration value="ESP"/&gt;
	 *               &lt;enumeration value="SWE"/&gt;
	 *               &lt;enumeration value="CHE"/&gt;
	 *             &lt;/restriction&gt;
	 *           &lt;/simpleType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "countryCode" })
	public static class CountryList {

		@XmlElement(name = "CountryCode", required = true)
		@JsonProperty("CountryCode")
		protected List<String> countryCode;

		/**
		 * Gets the value of the countryCode property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the countryCode property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getCountryCode().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * @return Objects of the following type(s) are allowed in the list
		 *         {@link String }
		 * 
		 */
		public List<String> getCountryCode() {
			if (countryCode == null) {
				countryCode = new ArrayList<String>();
			}
			return this.countryCode;
		}

	}

}
