//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.19 at 08:43:00 AM CST 
//


package com.newegg.marketplace.sdk.item.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="IsSuccess">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SellerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OperationType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ResponseDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Memo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResponseBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PageInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="TotalCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="TotalPageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="PageIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="PageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ManufacturerList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Manufacturer" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="IsRestricted">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                             &lt;enumeration value="0"/>
 *                                             &lt;enumeration value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="RestrictedSubcategoryList" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Subcategory" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;all>
 *                                                           &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                           &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/all>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="MappedNameList" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="MappedName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "NeweggAPIResponse")
public class GetManufacturerResponseV2 {

    @XmlElement(name = "IsSuccess", required = true)
    @JsonProperty("IsSuccess")
    protected boolean isSuccess;
    @XmlElement(name = "SellerID", required = true)
    @JsonProperty("SellerID")
    protected String sellerID;
    @XmlElement(name = "OperationType", required = true)
    @JsonProperty("OperationType")
    protected String operationType;
    @XmlElement(name = "ResponseDate", required = true)
    @JsonProperty("ResponseDate")
    protected String responseDate;
    @XmlElement(name = "Memo")
    @JsonProperty("Memo")
    protected String memo;
    @XmlElement(name = "ResponseBody", required = true)
    @JsonProperty("ResponseBody")
    protected GetManufacturerResponseV2.ResponseBody responseBody;

    /**
     * Gets the value of the isSuccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public boolean getIsSuccess() {
        return isSuccess;
    }

    /**
     * Sets the value of the isSuccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSuccess(boolean value) {
        this.isSuccess = value;
    }

    /**
     * Gets the value of the sellerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerID() {
        return sellerID;
    }

    /**
     * Sets the value of the sellerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerID(String value) {
        this.sellerID = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the responseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDate() {
        return responseDate;
    }

    /**
     * Sets the value of the responseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDate(String value) {
        this.responseDate = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemo(String value) {
        this.memo = value;
    }

    /**
     * Gets the value of the responseBody property.
     * 
     * @return
     *     possible object is
     *     {@link GetManufacturerResponseV2.ResponseBody }
     *     
     */
    public GetManufacturerResponseV2.ResponseBody getResponseBody() {
        return responseBody;
    }

    /**
     * Sets the value of the responseBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetManufacturerResponseV2.ResponseBody }
     *     
     */
    public void setResponseBody(GetManufacturerResponseV2.ResponseBody value) {
        this.responseBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PageInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="TotalCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="TotalPageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="PageIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="PageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ManufacturerList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Manufacturer" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="IsRestricted">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                                   &lt;enumeration value="0"/>
     *                                   &lt;enumeration value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="RestrictedSubcategoryList" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Subcategory" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;all>
     *                                                 &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                                 &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/all>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="MappedNameList" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="MappedName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pageInfo",
        "manufacturerList"
    })
    public static class ResponseBody {

        @XmlElement(name = "PageInfo", required = true)
        @JsonProperty("PageInfo")
        protected GetManufacturerResponseV2.ResponseBody.PageInfo pageInfo;
        @XmlElement(name = "ManufacturerList", required = true)
        //@JsonProperty("ManufacturerList")
        @JsonUnwrapped
        protected GetManufacturerResponseV2.ResponseBody.ManufacturerList manufacturerList;

        /**
         * Gets the value of the pageInfo property.
         * 
         * @return
         *     possible object is
         *     {@link GetManufacturerResponseV2.ResponseBody.PageInfo }
         *     
         */
        public GetManufacturerResponseV2.ResponseBody.PageInfo getPageInfo() {
            return pageInfo;
        }

        /**
         * Sets the value of the pageInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetManufacturerResponseV2.ResponseBody.PageInfo }
         *     
         */
        public void setPageInfo(GetManufacturerResponseV2.ResponseBody.PageInfo value) {
            this.pageInfo = value;
        }

        /**
         * Gets the value of the manufacturerList property.
         * 
         * @return
         *     possible object is
         *     {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList }
         *     
         */
        public GetManufacturerResponseV2.ResponseBody.ManufacturerList getManufacturerList() {
            return manufacturerList;
        }

        /**
         * Sets the value of the manufacturerList property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList }
         *     
         */
        public void setManufacturerList(GetManufacturerResponseV2.ResponseBody.ManufacturerList value) {
            this.manufacturerList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Manufacturer" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="IsRestricted">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *                         &lt;enumeration value="0"/>
         *                         &lt;enumeration value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="RestrictedSubcategoryList" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Subcategory" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;all>
         *                                       &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                                       &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/all>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="MappedNameList" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="MappedName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "manufacturer"
        })
        public static class ManufacturerList {

            @XmlElement(name = "Manufacturer", required = true)
            @JsonProperty("ManufacturerList")
            protected List<GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer> manufacturer;

            /**
             * Gets the value of the manufacturer property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the manufacturer property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getManufacturer().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer }
             * 
             * 
             */
            public List<GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer> getManufacturer() {
                if (manufacturer == null) {
                    manufacturer = new ArrayList<GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer>();
                }
                return this.manufacturer;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="IsRestricted">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
             *               &lt;enumeration value="0"/>
             *               &lt;enumeration value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="RestrictedSubcategoryList" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Subcategory" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;all>
             *                             &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                             &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/all>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="MappedNameList" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="MappedName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class Manufacturer {

                @XmlElement(name = "Name", required = true)
                @JsonProperty("Name")
                protected String name;
                @XmlElement(name = "IsRestricted")
                @JsonProperty("IsRestricted")
                protected int isRestricted;
                @XmlElement(name = "RestrictedSubcategoryList")
                //@JsonProperty("RestrictedSubcategoryList")
                @JsonUnwrapped
                protected GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList restrictedSubcategoryList;
                @XmlElement(name = "MappedNameList")
                //@JsonProperty("MappedNameList")
                @JsonUnwrapped
                protected GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.MappedNameList mappedNameList;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the isRestricted property.
                 * 
                 */
                public int getIsRestricted() {
                    return isRestricted;
                }

                /**
                 * Sets the value of the isRestricted property.
                 * 
                 */
                public void setIsRestricted(int value) {
                    this.isRestricted = value;
                }

                /**
                 * Gets the value of the restrictedSubcategoryList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList }
                 *     
                 */
                public GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList getRestrictedSubcategoryList() {
                    return restrictedSubcategoryList;
                }

                /**
                 * Sets the value of the restrictedSubcategoryList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList }
                 *     
                 */
                public void setRestrictedSubcategoryList(GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList value) {
                    this.restrictedSubcategoryList = value;
                }

                /**
                 * Gets the value of the mappedNameList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.MappedNameList }
                 *     
                 */
                public GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.MappedNameList getMappedNameList() {
                    return mappedNameList;
                }

                /**
                 * Sets the value of the mappedNameList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.MappedNameList }
                 *     
                 */
                public void setMappedNameList(GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.MappedNameList value) {
                    this.mappedNameList = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="MappedName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "mappedName"
                })
                public static class MappedNameList {

                    @XmlElement(name = "MappedName", required = true)
                    @JsonProperty("MappedNameList")
                    protected List<String> mappedName;

                    /**
                     * Gets the value of the mappedName property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the mappedName property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getMappedName().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getMappedName() {
                        if (mappedName == null) {
                            mappedName = new ArrayList<String>();
                        }
                        return this.mappedName;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Subcategory" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;all>
                 *                   &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *                   &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/all>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "subcategory"
                })
                public static class RestrictedSubcategoryList {

                    @XmlElement(name = "Subcategory")
                    @JsonProperty("RestrictedSubcategoryList")
                    protected List<GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList.Subcategory> subcategory;

                    /**
                     * Gets the value of the subcategory property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the subcategory property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getSubcategory().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList.Subcategory }
                     * 
                     * 
                     */
                    public List<GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList.Subcategory> getSubcategory() {
                        if (subcategory == null) {
                            subcategory = new ArrayList<GetManufacturerResponseV2.ResponseBody.ManufacturerList.Manufacturer.RestrictedSubcategoryList.Subcategory>();
                        }
                        return this.subcategory;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;all>
                     *         &lt;element name="SubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
                     *         &lt;element name="SubcategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/all>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {

                    })
                    public static class Subcategory {

                        @XmlElement(name = "SubcategoryID")
                        @JsonProperty("SubcategoryID")
                        protected int subcategoryID;
                        @XmlElement(name = "SubcategoryName", required = true)
                        @JsonProperty("SubcategoryName")
                        protected String subcategoryName;

                        /**
                         * Gets the value of the subcategoryID property.
                         * 
                         */
                        public int getSubcategoryID() {
                            return subcategoryID;
                        }

                        /**
                         * Sets the value of the subcategoryID property.
                         * 
                         */
                        public void setSubcategoryID(int value) {
                            this.subcategoryID = value;
                        }

                        /**
                         * Gets the value of the subcategoryName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSubcategoryName() {
                            return subcategoryName;
                        }

                        /**
                         * Sets the value of the subcategoryName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSubcategoryName(String value) {
                            this.subcategoryName = value;
                        }

                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="TotalCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="TotalPageCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="PageIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="PageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class PageInfo {

            @XmlElement(name = "TotalCount")
            @JsonProperty("TotalCount")
            protected int totalCount;
            @XmlElement(name = "TotalPageCount")
            @JsonProperty("TotalPageCount")
            protected int totalPageCount;
            @XmlElement(name = "PageIndex")
            @JsonProperty("PageIndex")
            protected int pageIndex;
            @XmlElement(name = "PageSize")
            @JsonProperty("PageSize")
            protected int pageSize;

            /**
             * Gets the value of the totalCount property.
             * 
             */
            public int getTotalCount() {
                return totalCount;
            }

            /**
             * Sets the value of the totalCount property.
             * 
             */
            public void setTotalCount(int value) {
                this.totalCount = value;
            }

            /**
             * Gets the value of the totalPageCount property.
             * 
             */
            public int getTotalPageCount() {
                return totalPageCount;
            }

            /**
             * Sets the value of the totalPageCount property.
             * 
             */
            public void setTotalPageCount(int value) {
                this.totalPageCount = value;
            }

            /**
             * Gets the value of the pageIndex property.
             * 
             */
            public int getPageIndex() {
                return pageIndex;
            }

            /**
             * Sets the value of the pageIndex property.
             * 
             */
            public void setPageIndex(int value) {
                this.pageIndex = value;
            }

            /**
             * Gets the value of the pageSize property.
             * 
             */
            public int getPageSize() {
                return pageSize;
            }

            /**
             * Sets the value of the pageSize property.
             * 
             */
            public void setPageSize(int value) {
                this.pageSize = value;
            }

        }

    }

}
