//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.22 at 09:14:10 AM CST 
//


package com.newegg.marketplace.sdk.item.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Condition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *               &lt;enumeration value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Value">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PriceList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Price" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="CountryCode">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="AUS"/>
 *                                   &lt;enumeration value="NZL"/>
 *                                   &lt;enumeration value="GBR"/>
 *                                   &lt;enumeration value="IRL"/>
 *                                   &lt;enumeration value="NLD"/>
 *                                   &lt;enumeration value="POL"/>
 *                                   &lt;enumeration value="IND"/>
 *                                   &lt;enumeration value="SGP"/>
 *                                   &lt;enumeration value="USA"/>
 *                                   &lt;enumeration value="HKG"/>
 *                                   &lt;enumeration value="MAC"/>
 *                                   &lt;enumeration value="IDN"/>
 *                                   &lt;enumeration value="PHL"/>
 *                                   &lt;enumeration value="KOR"/>
 *                                   &lt;enumeration value="THA"/>
 *                                   &lt;enumeration value="BRA"/>
 *                                   &lt;enumeration value="CHL"/>
 *                                   &lt;enumeration value="CHN"/>
 *                                   &lt;enumeration value="COL"/>
 *                                   &lt;enumeration value="CRI"/>
 *                                   &lt;enumeration value="DOM"/>
 *                                   &lt;enumeration value="ECU"/>
 *                                   &lt;enumeration value="SLV"/>
 *                                   &lt;enumeration value="GTM"/>
 *                                   &lt;enumeration value="HND"/>
 *                                   &lt;enumeration value="JAM"/>
 *                                   &lt;enumeration value="MEX"/>
 *                                   &lt;enumeration value="NIC"/>
 *                                   &lt;enumeration value="PAN"/>
 *                                   &lt;enumeration value="ISR"/>
 *                                   &lt;enumeration value="SAU"/>
 *                                   &lt;enumeration value="TUR"/>
 *                                   &lt;enumeration value="ARE"/>
 *                                   &lt;enumeration value="AUT"/>
 *                                   &lt;enumeration value="BEL"/>
 *                                   &lt;enumeration value="BGR"/>
 *                                   &lt;enumeration value="DNK"/>
 *                                   &lt;enumeration value="FIN"/>
 *                                   &lt;enumeration value="FRA"/>
 *                                   &lt;enumeration value="DEU"/>
 *                                   &lt;enumeration value="GRC"/>
 *                                   &lt;enumeration value="HUN"/>
 *                                   &lt;enumeration value="ITA"/>
 *                                   &lt;enumeration value="LVA"/>
 *                                   &lt;enumeration value="LUX"/>
 *                                   &lt;enumeration value="MCO"/>
 *                                   &lt;enumeration value="NOR"/>
 *                                   &lt;enumeration value="PRT"/>
 *                                   &lt;enumeration value="SVK"/>
 *                                   &lt;enumeration value="SVN"/>
 *                                   &lt;enumeration value="ESP"/>
 *                                   &lt;enumeration value="SWE"/>
 *                                   &lt;enumeration value="CHE"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Currency">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="AED"/>
 *                                   &lt;enumeration value="AUD"/>
 *                                   &lt;enumeration value="BGN"/>
 *                                   &lt;enumeration value="BRL"/>
 *                                   &lt;enumeration value="CHF"/>
 *                                   &lt;enumeration value="CNY"/>
 *                                   &lt;enumeration value="COP"/>
 *                                   &lt;enumeration value="CRC"/>
 *                                   &lt;enumeration value="DKK"/>
 *                                   &lt;enumeration value="DOP"/>
 *                                   &lt;enumeration value="EUR"/>
 *                                   &lt;enumeration value="GBP"/>
 *                                   &lt;enumeration value="HKD"/>
 *                                   &lt;enumeration value="HNL"/>
 *                                   &lt;enumeration value="HUF"/>
 *                                   &lt;enumeration value="IDR"/>
 *                                   &lt;enumeration value="ILS"/>
 *                                   &lt;enumeration value="INR"/>
 *                                   &lt;enumeration value="JMD"/>
 *                                   &lt;enumeration value="KRW"/>
 *                                   &lt;enumeration value="MOP"/>
 *                                   &lt;enumeration value="MXN"/>
 *                                   &lt;enumeration value="NIO"/>
 *                                   &lt;enumeration value="NOK"/>
 *                                   &lt;enumeration value="NZD"/>
 *                                   &lt;enumeration value="PAB"/>
 *                                   &lt;enumeration value="PHP"/>
 *                                   &lt;enumeration value="PLN"/>
 *                                   &lt;enumeration value="SAR"/>
 *                                   &lt;enumeration value="SEK"/>
 *                                   &lt;enumeration value="SGD"/>
 *                                   &lt;enumeration value="THB"/>
 *                                   &lt;enumeration value="TRY"/>
 *                                   &lt;enumeration value="USD"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Active" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="MSRP" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="99999.99"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="MAP" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="99999.99"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CheckoutMAP" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="SellingPrice" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;maxInclusive value="99999.99"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                   &lt;minExclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="EnableFreeShipping" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ItemPriceInfo")
public class UpdateItemPriceRequest {

    @XmlElement(name = "Condition", defaultValue = "1")
    @JsonProperty("Condition")
    protected Integer condition;
    @XmlElement(name = "Type")
    @JsonProperty("Type")
    protected int type;
    @XmlElement(name = "Value", required = true)
    @JsonProperty("Value")
    protected String value;
    @XmlElement(name = "PriceList", required = true)
    @JsonProperty("PriceList")
    protected UpdateItemPriceRequest.PriceList priceList;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCondition(Integer value) {
        this.condition = value;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(int value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the priceList property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateItemPriceRequest.PriceList }
     *     
     */
    public UpdateItemPriceRequest.PriceList getPriceList() {
        return priceList;
    }

    /**
     * Sets the value of the priceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateItemPriceRequest.PriceList }
     *     
     */
    public void setPriceList(UpdateItemPriceRequest.PriceList value) {
        this.priceList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Price" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="CountryCode">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="AUS"/>
     *                         &lt;enumeration value="NZL"/>
     *                         &lt;enumeration value="GBR"/>
     *                         &lt;enumeration value="IRL"/>
     *                         &lt;enumeration value="NLD"/>
     *                         &lt;enumeration value="POL"/>
     *                         &lt;enumeration value="IND"/>
     *                         &lt;enumeration value="SGP"/>
     *                         &lt;enumeration value="USA"/>
     *                         &lt;enumeration value="HKG"/>
     *                         &lt;enumeration value="MAC"/>
     *                         &lt;enumeration value="IDN"/>
     *                         &lt;enumeration value="PHL"/>
     *                         &lt;enumeration value="KOR"/>
     *                         &lt;enumeration value="THA"/>
     *                         &lt;enumeration value="BRA"/>
     *                         &lt;enumeration value="CHL"/>
     *                         &lt;enumeration value="CHN"/>
     *                         &lt;enumeration value="COL"/>
     *                         &lt;enumeration value="CRI"/>
     *                         &lt;enumeration value="DOM"/>
     *                         &lt;enumeration value="ECU"/>
     *                         &lt;enumeration value="SLV"/>
     *                         &lt;enumeration value="GTM"/>
     *                         &lt;enumeration value="HND"/>
     *                         &lt;enumeration value="JAM"/>
     *                         &lt;enumeration value="MEX"/>
     *                         &lt;enumeration value="NIC"/>
     *                         &lt;enumeration value="PAN"/>
     *                         &lt;enumeration value="ISR"/>
     *                         &lt;enumeration value="SAU"/>
     *                         &lt;enumeration value="TUR"/>
     *                         &lt;enumeration value="ARE"/>
     *                         &lt;enumeration value="AUT"/>
     *                         &lt;enumeration value="BEL"/>
     *                         &lt;enumeration value="BGR"/>
     *                         &lt;enumeration value="DNK"/>
     *                         &lt;enumeration value="FIN"/>
     *                         &lt;enumeration value="FRA"/>
     *                         &lt;enumeration value="DEU"/>
     *                         &lt;enumeration value="GRC"/>
     *                         &lt;enumeration value="HUN"/>
     *                         &lt;enumeration value="ITA"/>
     *                         &lt;enumeration value="LVA"/>
     *                         &lt;enumeration value="LUX"/>
     *                         &lt;enumeration value="MCO"/>
     *                         &lt;enumeration value="NOR"/>
     *                         &lt;enumeration value="PRT"/>
     *                         &lt;enumeration value="SVK"/>
     *                         &lt;enumeration value="SVN"/>
     *                         &lt;enumeration value="ESP"/>
     *                         &lt;enumeration value="SWE"/>
     *                         &lt;enumeration value="CHE"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Currency">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="AED"/>
     *                         &lt;enumeration value="AUD"/>
     *                         &lt;enumeration value="BGN"/>
     *                         &lt;enumeration value="BRL"/>
     *                         &lt;enumeration value="CHF"/>
     *                         &lt;enumeration value="CNY"/>
     *                         &lt;enumeration value="COP"/>
     *                         &lt;enumeration value="CRC"/>
     *                         &lt;enumeration value="DKK"/>
     *                         &lt;enumeration value="DOP"/>
     *                         &lt;enumeration value="EUR"/>
     *                         &lt;enumeration value="GBP"/>
     *                         &lt;enumeration value="HKD"/>
     *                         &lt;enumeration value="HNL"/>
     *                         &lt;enumeration value="HUF"/>
     *                         &lt;enumeration value="IDR"/>
     *                         &lt;enumeration value="ILS"/>
     *                         &lt;enumeration value="INR"/>
     *                         &lt;enumeration value="JMD"/>
     *                         &lt;enumeration value="KRW"/>
     *                         &lt;enumeration value="MOP"/>
     *                         &lt;enumeration value="MXN"/>
     *                         &lt;enumeration value="NIO"/>
     *                         &lt;enumeration value="NOK"/>
     *                         &lt;enumeration value="NZD"/>
     *                         &lt;enumeration value="PAB"/>
     *                         &lt;enumeration value="PHP"/>
     *                         &lt;enumeration value="PLN"/>
     *                         &lt;enumeration value="SAR"/>
     *                         &lt;enumeration value="SEK"/>
     *                         &lt;enumeration value="SGD"/>
     *                         &lt;enumeration value="THB"/>
     *                         &lt;enumeration value="TRY"/>
     *                         &lt;enumeration value="USD"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Active" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="MSRP" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="99999.99"/>
     *                         &lt;fractionDigits value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="MAP" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="99999.99"/>
     *                         &lt;fractionDigits value="2"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CheckoutMAP" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SellingPrice" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;maxInclusive value="99999.99"/>
     *                         &lt;fractionDigits value="2"/>
     *                         &lt;minExclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="EnableFreeShipping" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "price"
    })
    public static class PriceList {

        @XmlElement(name = "Price", required = true)
        @JsonProperty("Price")
        protected List<UpdateItemPriceRequest.PriceList.Price> price;

        /**
         * Gets the value of the price property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the price property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrice().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UpdateItemPriceRequest.PriceList.Price }
         * 
         * 
         */
        public List<UpdateItemPriceRequest.PriceList.Price> getPrice() {
            if (price == null) {
                price = new ArrayList<UpdateItemPriceRequest.PriceList.Price>();
            }
            return this.price;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="CountryCode">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="AUS"/>
         *               &lt;enumeration value="NZL"/>
         *               &lt;enumeration value="GBR"/>
         *               &lt;enumeration value="IRL"/>
         *               &lt;enumeration value="NLD"/>
         *               &lt;enumeration value="POL"/>
         *               &lt;enumeration value="IND"/>
         *               &lt;enumeration value="SGP"/>
         *               &lt;enumeration value="USA"/>
         *               &lt;enumeration value="HKG"/>
         *               &lt;enumeration value="MAC"/>
         *               &lt;enumeration value="IDN"/>
         *               &lt;enumeration value="PHL"/>
         *               &lt;enumeration value="KOR"/>
         *               &lt;enumeration value="THA"/>
         *               &lt;enumeration value="BRA"/>
         *               &lt;enumeration value="CHL"/>
         *               &lt;enumeration value="CHN"/>
         *               &lt;enumeration value="COL"/>
         *               &lt;enumeration value="CRI"/>
         *               &lt;enumeration value="DOM"/>
         *               &lt;enumeration value="ECU"/>
         *               &lt;enumeration value="SLV"/>
         *               &lt;enumeration value="GTM"/>
         *               &lt;enumeration value="HND"/>
         *               &lt;enumeration value="JAM"/>
         *               &lt;enumeration value="MEX"/>
         *               &lt;enumeration value="NIC"/>
         *               &lt;enumeration value="PAN"/>
         *               &lt;enumeration value="ISR"/>
         *               &lt;enumeration value="SAU"/>
         *               &lt;enumeration value="TUR"/>
         *               &lt;enumeration value="ARE"/>
         *               &lt;enumeration value="AUT"/>
         *               &lt;enumeration value="BEL"/>
         *               &lt;enumeration value="BGR"/>
         *               &lt;enumeration value="DNK"/>
         *               &lt;enumeration value="FIN"/>
         *               &lt;enumeration value="FRA"/>
         *               &lt;enumeration value="DEU"/>
         *               &lt;enumeration value="GRC"/>
         *               &lt;enumeration value="HUN"/>
         *               &lt;enumeration value="ITA"/>
         *               &lt;enumeration value="LVA"/>
         *               &lt;enumeration value="LUX"/>
         *               &lt;enumeration value="MCO"/>
         *               &lt;enumeration value="NOR"/>
         *               &lt;enumeration value="PRT"/>
         *               &lt;enumeration value="SVK"/>
         *               &lt;enumeration value="SVN"/>
         *               &lt;enumeration value="ESP"/>
         *               &lt;enumeration value="SWE"/>
         *               &lt;enumeration value="CHE"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Currency">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="AED"/>
         *               &lt;enumeration value="AUD"/>
         *               &lt;enumeration value="BGN"/>
         *               &lt;enumeration value="BRL"/>
         *               &lt;enumeration value="CHF"/>
         *               &lt;enumeration value="CNY"/>
         *               &lt;enumeration value="COP"/>
         *               &lt;enumeration value="CRC"/>
         *               &lt;enumeration value="DKK"/>
         *               &lt;enumeration value="DOP"/>
         *               &lt;enumeration value="EUR"/>
         *               &lt;enumeration value="GBP"/>
         *               &lt;enumeration value="HKD"/>
         *               &lt;enumeration value="HNL"/>
         *               &lt;enumeration value="HUF"/>
         *               &lt;enumeration value="IDR"/>
         *               &lt;enumeration value="ILS"/>
         *               &lt;enumeration value="INR"/>
         *               &lt;enumeration value="JMD"/>
         *               &lt;enumeration value="KRW"/>
         *               &lt;enumeration value="MOP"/>
         *               &lt;enumeration value="MXN"/>
         *               &lt;enumeration value="NIO"/>
         *               &lt;enumeration value="NOK"/>
         *               &lt;enumeration value="NZD"/>
         *               &lt;enumeration value="PAB"/>
         *               &lt;enumeration value="PHP"/>
         *               &lt;enumeration value="PLN"/>
         *               &lt;enumeration value="SAR"/>
         *               &lt;enumeration value="SEK"/>
         *               &lt;enumeration value="SGD"/>
         *               &lt;enumeration value="THB"/>
         *               &lt;enumeration value="TRY"/>
         *               &lt;enumeration value="USD"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Active" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="MSRP" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="99999.99"/>
         *               &lt;fractionDigits value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="MAP" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="99999.99"/>
         *               &lt;fractionDigits value="2"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CheckoutMAP" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SellingPrice" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;maxInclusive value="99999.99"/>
         *               &lt;fractionDigits value="2"/>
         *               &lt;minExclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="EnableFreeShipping" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Price {

            @XmlElement(name = "CountryCode", required = true)
            @JsonProperty("CountryCode")
            protected String countryCode;
            @XmlElement(name = "Currency", required = true)
            @JsonProperty("Currency")
            protected String currency;
            @XmlElement(name = "Active")
            @JsonProperty("Active")
            protected Integer active;
            @XmlElement(name = "MSRP")
            @JsonProperty("MSRP")
            protected BigDecimal msrp;
            @XmlElement(name = "MAP")
            @JsonProperty("MAP")
            protected BigDecimal map;
            @XmlElement(name = "CheckoutMAP")
            @JsonProperty("CheckoutMAP")
            protected Integer checkoutMAP;
            @XmlElement(name = "SellingPrice")
            @JsonProperty("SellingPrice")
            protected BigDecimal sellingPrice;
            @XmlElement(name = "EnableFreeShipping")
            @JsonProperty("EnableFreeShipping")
            protected Integer enableFreeShipping;

            /**
             * Gets the value of the countryCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryCode() {
                return countryCode;
            }

            /**
             * Sets the value of the countryCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryCode(String value) {
                this.countryCode = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            /**
             * Gets the value of the active property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getActive() {
                return active;
            }

            /**
             * Sets the value of the active property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setActive(Integer value) {
                this.active = value;
            }

            /**
             * Gets the value of the msrp property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMSRP() {
                return msrp;
            }

            /**
             * Sets the value of the msrp property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMSRP(BigDecimal value) {
                this.msrp = value;
            }

            /**
             * Gets the value of the map property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMAP() {
                return map;
            }

            /**
             * Sets the value of the map property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMAP(BigDecimal value) {
                this.map = value;
            }

            /**
             * Gets the value of the checkoutMAP property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCheckoutMAP() {
                return checkoutMAP;
            }

            /**
             * Sets the value of the checkoutMAP property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCheckoutMAP(Integer value) {
                this.checkoutMAP = value;
            }

            /**
             * Gets the value of the sellingPrice property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSellingPrice() {
                return sellingPrice;
            }

            /**
             * Sets the value of the sellingPrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSellingPrice(BigDecimal value) {
                this.sellingPrice = value;
            }

            /**
             * Gets the value of the enableFreeShipping property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getEnableFreeShipping() {
                return enableFreeShipping;
            }

            /**
             * Sets the value of the enableFreeShipping property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setEnableFreeShipping(Integer value) {
                this.enableFreeShipping = value;
            }

        }

    }

}
